version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
    timezone: America/Chicago
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - ">= 8.a, < 9"
  - dependency-name: husky
    versions:
    - ">= 6.a, < 7"
  - dependency-name: lerna
    versions:
    - ">= 4.a, < 5"
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - ">= 4.a, < 5"
  - dependency-name: "@types/node"
    versions:
    - ">= 14.a, < 15"
  - dependency-name: "@stoplight/json-schema-sampler"
    versions:
    - 0.2.0
  - dependency-name: "@stoplight/types"
    versions:
    - 11.10.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: gavel
    versions:
    - 10.0.0
    - 10.0.1
  - dependency-name: ajv
    versions:
    - 7.0.4
    - 7.1.0
    - 7.1.1
  - dependency-name: json-schema-faker
    versions:
    - 0.5.0-rcv.33
  - dependency-name: "@stoplight/http-spec"
    versions:
    - 3.2.5
  - dependency-name: ts-jest
    versions:
    - 26.5.1
  - dependency-name: faker
    versions:
    - 5.2.0
    - 5.3.1
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.0
    - 4.14.1
  - dependency-name: "@types/faker"
    versions:
    - 5.1.6
  - dependency-name: "glob-fs"
    versions:
    - 0.1.7
  registries:
  - npm-registry-registry-npmjs-org
