version: '3.9'
services:
  openprism:
    image: openprism:demo
    command: 'mock -h openprism /tmp/specification/storage/resource-manager/Microsoft.Storage/stable/2021-08-01/storage.json'
    networks:
      - openprism
    expose:
      - '4010'
  nginx-tls-proxy:
    image: nginx:mainline
    volumes:
      # Override default config to act as TLS proxy
      - ./conf/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./conf/nginx/snippets:/etc/nginx/snippets:ro
      # Self-signed certificates etc in here
      - ./conf/tls:/etc/tls:ro
    depends_on:
      - openprism
    networks:
      - openprism
    ports:
      - '443:443'
networks:
  openprism: